In [44]:
import numpy as np


maze = np.random.randint(0, 2, (6,6))
maze[0,0] = 2
maze[5,5] = 3

maze

array([[2, 0, 1, 0, 1, 0],
       [1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 1, 1],
       [0, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0, 1],
       [0, 1, 0, 0, 0, 3]])

In [83]:
def direction2action(delta_x, delta_y):
    if (delta_x == 0):
        if (delta_y == 1):
            return 2
        elif (delta_y == 0):
            return 0
        elif (delta_y == -1):
            return 1
    elif (delta_x == 1 and delta_y == 0):
        return 4
    elif (delta_x == -1 and delta_y == 0):
        return 3
    raise Exception("Unknown direction")

def action2direction(action):
    a2d = [(0,0), (0, -1), (0, 1), (-1, 0), (1, 0)]
    return a2d[action]

maze[2,3] = 0
maze

array([[2, 0, 1, 0, 1, 0],
       [1, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 1, 1],
       [0, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0, 1],
       [0, 1, 0, 0, 0, 3]])

In [88]:
class BFS():
    def solve(self, maze):
        """
        param: maze: numpy.matrix
        return: history: [numpy.matrix, action]
        return: solvable: boolean
        """
        
        # reset param
        self._reset(maze)
        
        self.search_maze = maze.copy()
        self.visited = maze.copy()
        self.visited[np.where(self.visited==3)] = 0
        self.visited[np.where(self.visited==2)] = 0
        
        search = []
        history = []
        
        # start BFS
        search.append((0,0))
        self.visited[0,0] = 1
        
        while(len(search) > 0):
            x,y = search[0]
            search = search[1:]
            
            if (self.search_maze[y,x] == 3):
                self.search_maze[np.where(self.search_maze==2)] = 0
                hx, hy = x, y
                while True:
                    if (hx == 0 and hy == 0):
                        break
                    thisx, thisy = self.parent[hy, hx]
                    action = direction2action(hx-thisx, hy-thisy)
                    if (self.search_maze[hy, hx] == 2):
                        self.search_maze[hy, hx] = 0
                    self.search_maze[thisy, thisx] = 2
                    hx, hy = thisx, thisy
                    history.append((self.search_maze.copy(), action))
                break
            neibs = self._get_neighbour((x,y))
            for n in neibs:
                nx, ny = n
                self.visited[ny, nx] = 1
                self.parent[ny, nx] = (x,y)
                search.append(n)
        
        history.reverse()
        solvable = True
        if len(history) == 0:
            solvable = False
        return history, solvable    
            
        
    def _get_neighbour(self, pos):
        h, w = self.search_maze.shape
        x,y = pos
        delta_x = [0, 0, -1, 1]
        delta_y = [-1, 1, 0, 0]
        neibs = []
        
        for i in range(4):
            new_x = x + delta_x[i]
            new_y = y + delta_y[i]
            if (0<= new_x < w and 0 <= new_y < h and self.visited[new_y][new_x] == 0):
                neibs.append((new_x, new_y))
        return neibs
        
        
    def _reset(self, maze):
        self.parent = np.array([[(-1,-1) for i in range(6)] for i in range(6)])
        self.pos = (0,0)
        self.h, self.w = maze.shape

bfs = BFS()
bfs.solve(maze)

[[2 0 1 0 1 0]
 [1 0 0 1 0 1]
 [0 1 0 0 1 1]
 [0 0 1 0 1 0]
 [1 0 1 0 0 1]
 [0 1 0 0 0 3]] 4
[[0 2 1 0 1 0]
 [1 0 0 1 0 1]
 [0 1 0 0 1 1]
 [0 0 1 0 1 0]
 [1 0 1 0 0 1]
 [0 1 0 0 0 3]] 2
[[0 0 1 0 1 0]
 [1 2 0 1 0 1]
 [0 1 0 0 1 1]
 [0 0 1 0 1 0]
 [1 0 1 0 0 1]
 [0 1 0 0 0 3]] 4
[[0 0 1 0 1 0]
 [1 0 2 1 0 1]
 [0 1 0 0 1 1]
 [0 0 1 0 1 0]
 [1 0 1 0 0 1]
 [0 1 0 0 0 3]] 2
[[0 0 1 0 1 0]
 [1 0 0 1 0 1]
 [0 1 2 0 1 1]
 [0 0 1 0 1 0]
 [1 0 1 0 0 1]
 [0 1 0 0 0 3]] 4
[[0 0 1 0 1 0]
 [1 0 0 1 0 1]
 [0 1 0 2 1 1]
 [0 0 1 0 1 0]
 [1 0 1 0 0 1]
 [0 1 0 0 0 3]] 2
[[0 0 1 0 1 0]
 [1 0 0 1 0 1]
 [0 1 0 0 1 1]
 [0 0 1 2 1 0]
 [1 0 1 0 0 1]
 [0 1 0 0 0 3]] 2
[[0 0 1 0 1 0]
 [1 0 0 1 0 1]
 [0 1 0 0 1 1]
 [0 0 1 0 1 0]
 [1 0 1 2 0 1]
 [0 1 0 0 0 3]] 2
[[0 0 1 0 1 0]
 [1 0 0 1 0 1]
 [0 1 0 0 1 1]
 [0 0 1 0 1 0]
 [1 0 1 0 0 1]
 [0 1 0 2 0 3]] 4
[[0 0 1 0 1 0]
 [1 0 0 1 0 1]
 [0 1 0 0 1 1]
 [0 0 1 0 1 0]
 [1 0 1 0 0 1]
 [0 1 0 0 2 3]] 4


In [55]:
def BasicMiniGridEnv():
    def __init__(self, maze=None):
        """
        param: maze: numpy.matrix
        """
        self.maze = maze
        self.h, self.w = maze.shape

(1, 2)

In [4]:
import torch
import numpy as np

a = torch.tensor([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]], dtype=torch.float32)
dl = torch.utils.data.DataLoader(dataset=a, batch_size=1, shuffle=True)
for i, d in enumerate(dl):
    print(i, ":", d.view(-1, 6))

print("End")
# print(torch.randn_like(a))

0 : tensor([[ 7.,  8.,  9., 10., 11., 12.]])
1 : tensor([[1., 2., 3., 4., 5., 6.]])
End


In [21]:
import numpy as np
a = np.matrix([[1,2],[3,4]])
list(np.where(a==3)) == (1,0)
# print(x, y)

False